<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms> <!-- NotifyIcon 用のみ -->
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <AssemblyName>TNDrop</AssemblyName>
    <RootNamespace>TNDrop</RootNamespace>
    <Version>1.2.1</Version>
    <Authors>HIROKI TANODA (TND)</Authors>
    <Copyright>Copyright (c) 2026 HIROKI TANODA (TND). All rights reserved.</Copyright>
    <ApplicationIcon>..\..\assets\app.ico</ApplicationIcon>
    <SatelliteResourceLanguages>ja;en</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.*" />
  </ItemGroup>
</Project>
